export const productsList = [
  {
    id: 1,
    productName: "iPhone 14 Pro",
    brand: "Apple",
    img: "https://th.bing.com/th/id/OIP.wKEvIhL5zIE1b5W4kf3PNgHaHa?w=197&h=197&c=7&r=0&o=5&pid=1.7",
    price: 999.99,
  },
  {
    id: 2,
    productName: "Galaxy S23 Ultra",
    brand: "Samsung",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-ultra-5g-1.jpg",
    price: 899.99,
  },
  {
    id: 3,
    productName: "MacBook Pro 14",
    brand: "Apple",
    img: "https://th.bing.com/th/id/OIP.Y9tUX5s3zlLqHF5wR2YDNQHaEK?w=274&h=180&c=7&r=0&o=5&pid=1.7",
    price: 1499.99,
  },
  {
    id: 4,
    productName: "AirPods Pro",
    brand: "Apple",
    img: "https://th.bing.com/th/id/OIP.jMQgwCqMdQV7XBfxyScmtwHaF7?w=192&h=180&c=7&r=0&o=5&pid=1.7",
    price: 249.99,
  },
  {
    id: 5,
    productName: "iPad Pro",
    brand: "Apple",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2022-1.jpg",
    price: 799.99,
  },
  {
    id: 6,
    productName: "PlayStation 5",
    brand: "Sony",
    img: "https://th.bing.com/th/id/OIP.y_gegDFlmh4QWwsNHsmT3AHaE8?w=270&h=180&c=7&r=0&o=5&pid=1.7",
    price: 499.99,
  },
  {
    id: 7,
    productName: "Xbox Series X",
    brand: "Microsoft",
    img: "https://th.bing.com/th/id/OIP.jEvN4jOofeeiiLIm3d_oRAHaEK?w=315&h=180&c=7&r=0&o=5&pid=1.7",
    price: 499.99,
  },
  {
    id: 8,
    productName: "Galaxy Watch 5",
    brand: "Samsung",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-watch5-2.jpg",
    price: 279.99,
  },
  {
    id: 9,
    productName: "Surface Laptop 5",
    brand: "Microsoft",
    img: "https://th.bing.com/th/id/OIP.xv6eaLMwOxrhO9jsg1JtiQHaEK?w=300&h=180&c=7&r=0&o=5&pid=1.7",
    price: 999.99,
  },
  {
    id: 10,
    productName: "Google Pixel 7 Pro",
    brand: "Google",
    img: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel7-pro-2.jpg",
    price: 899.99,
  },
];
